language: java
./gradlew -Dhttps.protocols=TLSv1.2 check
before_install:
# - "export DISPLAY=:99.0"
# - "sh -e /etc/init.d/xvfb start"
 - cd ..
 - git clone https://github.com/Canadensys/canadensys-data-access
 - cd canadensys-data-access
 - git fetch --tags
 - git checkout tags/2.16.0
 - mvn clean install
 - cd ..
 - cd vascan
 - mv config/local/vascan-config.properties.example config/local/vascan-config.properties
 - mv config/local/version.properties.example config/local/version.properties
# script:
#  - ./gradlew check
#  - ./gradlew -daemon runIntegrationTest
# jdk7 requires Precise, see https://github.com/travis-ci/travis-ci/issues/8503
matrix:
 include:
  - jdk: oraclejdk8
    dist: trusty
  - jdk: oraclejdk7
    dist: precise
  - jdk: openjdk7
    dist: precise

# openjdk7 requires hostname see https://github.com/travis-ci/travis-ci/issues/5227
addons:
 hostname: vascan.dev
