language: java
before_install:
 - chmod +x gradlew
 - cd ..
 - git clone https://github.com/Canadensys/canadensys-data-access
 - cd canadensys-data-access
 - git fetch --tags
 - git checkout tags/2.17.2
 - mvn -Dhttps.protocols=TLSv1.2 clean install
 - cd ..
 - cd vascan
 - mv config/local/vascan-config.properties.example config/local/vascan-config.properties
 - mv config/local/version.properties.example config/local/version.properties
# script:
#  - ./gradlew check
#  - ./gradlew -daemon runIntegrationTest
jdk:
  - oraclejdk8
  - openjdk8

# openjdk7 requires hostname see https://github.com/travis-ci/travis-ci/issues/5227
addons:
 hostname: vascan.dev
