language: java
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - cd ..
 - git clone https://github.com/Canadensys/canadensys-data-access
 - cd canadensys-data-access
 - git fetch --tags
 - git checkout tags/2.12.2
 - mvn clean install
 - cd ..
 - git clone https://github.com/Canadensys/canadensys-view-includes 
 - cd vascan
 - mv config/local/vascan-config.properties.example config/local/vascan-config.properties
 - mv config/local/version.properties.example config/local/version.properties
# script:
#  - ./gradlew check
#  - ./gradlew -daemon runIntegrationTest
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
